### ISSUE TITLE
ncbi labeled sample data

### ISSUE THREAD

**Issue by qiutzh** [XinyuanWangCS/PromptAgent#2]
Hi, can you provide a labeled sample data for the NCBI named entity recognition task? I want to test it on other datasets.

**Comment by XinyuanWangCS** [comment]
Hi, are you saying the original dataset of NCBI? It can be acquired from huggingface: https://huggingface.co/datasets/ncbi_disease You can check PromptAgent/src/tasks/ncbi.py, which contains the code of loading and calculating metric.

**Comment by qiutzh** [comment]
Thanks, I found some clues from the following code. good job~
```python
def load_task_dataset(self, data_dir):
    return load_dataset("ncbi_disease").filter(lambda example: len(example["ner_tags"]) > 0)
```

**Comment by qiutzh** [comment]
Hello, when I performing prompt word optimization for the entity recognition task, an error was reported:
```shell
Traceback (most recent call last):
  File "D:\Program\ProjectByPython\reference\llm-related\optimize-based\PromptAgent\src\main.py", line 67, in <module>
    main(args)
  File "D:\Program\ProjectByPython\reference\llm-related\optimize-based\PromptAgent\src\main.py", line 62, in main
    agent.run(init_state=args['init_prompt'], iteration_num=args['iteration_num'])
  File "D:\Program\ProjectByPython\reference\llm-related\optimize-based\PromptAgent\src\prompt_optim_agent\agent.py", line 129, in run
    states, result_dict = self.search_algo.search(init_state=init_state, iteration_num=iteration_num)
  File "D:\Program\ProjectByPython\reference\llm-related\optimize-based\PromptAgent\src\prompt_optim_agent\search_algo\mcts.py", line 304, in search
    path, cum_rewards = self.iterate(self.root)
  File "D:\Program\ProjectByPython\reference\llm-related\optimize-based\PromptAgent\src\prompt_optim_agent\search_algo\mcts.py", line 283, in iterate
    self._simulate(path)
  File "D:\Program\ProjectByPython\reference\llm-related\optimize-based\PromptAgent\src\prompt_optim_agent\search_algo\mcts.py", line 250, in _simulate
    node = node.children[self.simulate_choice(rewards)]
  File "D:\Program\ProjectByPython\reference\llm-related\optimize-based\PromptAgent\src\prompt_optim_agent\search_algo\mcts.py", line 138, in simulate_choice
    return np.argmax(x)
  File "D:\Software\Develop\miniconda3\envs\py39_nlp\lib\site-packages\numpy\core\fromnumeric.py", line 1229, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out, **kwds)
  File "D:\Software\Develop\miniconda3\envs\py39_nlp\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "D:\Software\Develop\miniconda3\envs\py39_nlp\lib\site-packages\numpy\core\fromnumeric.py", line 45, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
```

I am using the following parameter configuration:
```shell
python src/main.py --task_name ncbi --search_algo mcts --batch_size 5 --depth_limit 5 --train_size 70 --eval_size 50 --test_size 0 --seed 42 --train_shuffle True --iteration_num 10 --expand_width 3 --post_instruction False --pred_model gpt-3.5-turbo --optim_model gpt-4 --log_dir logs/ --data_dir "" --init_prompt "Extract the disease or condition from the sentence, if any is mentioned." --api_key "your_api_key"
````

Is this caused by the default parameter configuration? Do you remember your default parameter settings? I didn't find the reference settings in the paper.

**Comment by XinyuanWangCS** [comment]
I re-cloned the repo and test your command. It works on my pc. I am not sure why you meet this issue without further details. 

Here is one of the command in the experiment:
`python src/main.py --search_algo mcts --pred_model gpt-3.5-turbo --log_dir logs/ --post_instruction False --train_shuffle True --batch_size 5 --expand_width 3 --iteration_num 12 --depth_limit 8 --task_name ncbi --init_prompt "Extract the disease or condition from the sentence, if any is mentioned." --optim_model gpt-4 --train_size 2000 --eval_size 150 --test_size 940 --api_key `

Here is a simplified command to save you some time:
`python src/main.py --search_algo mcts --pred_model gpt-3.5-turbo --log_dir logs/ --post_instruction False --train_shuffle True --batch_size 2 --expand_width 2 --iteration_num 2 --depth_limit 3 --task_name ncbi --init_prompt "Extract the disease or condition from the sentence, if any is mentioned." --optim_model gpt-4 --train_size 2000 --eval_size 10 --test_size 10 --api_key `

**Comment by qiutzh** [comment]
ok, thank you~
